### ISSUE TITLE
Prerequisites: Visual Studio

### ISSUE THREAD

**Issue by ellipticview** [akosbalasko/yarle#104]
Getting this error message on Windows:

```

C:\A0\yarle-master>npm i

> node-expat@2.3.18 install C:\A0\yarle-master\node_modules\node-expat
> node-gyp rebuild


C:\A0\yarle-master\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\nvm\\v12.13.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\A0\yarle-master\node_modules\node-expat
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-11-15T09_29_06_676Z-debug.log

C:\A0\yarle-master>
```

**Comment by akosbalasko** [comment]
Hi @ellipticview !

please install Microsoft's windows-build-tools as it is detailed here, in "On windows section, opt 1:
https://github.com/nodejs/node-gyp#on-windows

**Comment by akosbalasko** [comment]
Readme extended, please reopen this issue, if you still have troubles with installation.

**Comment by ellipticview** [comment]
Followed the instructions, but still no success (see below).
So to convert my Evernote files now I have installed:

- node
- python 3.8 from the Microsoft store
- Microsoft visual studio
- python 2.7 (dependency for the lib above)

That is quite a runtime stack for a file conversion utility! Isn't there a way to reduce this to only node?

This is the current output:

```
C:\A0\yarle-master>npm i

> node-expat@2.3.18 install C:\A0\yarle-master\node_modules\node-expat
> node-gyp rebuild


C:\A0\yarle-master\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! find VS
gyp ERR! find VS msvs_version not set from command line or npm config
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2017 (15.9.28307.1300) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - missing any Windows SDK
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Users\USERNAME\AppData\Roaming\nvm\v12.13.1\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:302:5)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\USERNAME\\AppData\\Roaming\\nvm\\v12.13.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\A0\yarle-master\node_modules\node-expat
gyp ERR! node -v v12.13.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-expat@2.3.18 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.18 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-11-15T15_43_07_879Z-debug.log

```

**Comment by akosbalasko** [comment]
You definitely don't have to install Visual Studio. 
please follow installation instructions described here: 

https://github.com/nodejs/node-gyp

And yes, it is mandatory, because Enex is an XML, and in order to parse it yarle uses an xml parser which is mainly a wrapper of a c++ packages which must be rebuilt for the platform because C++ is not platform-independent language.

**Comment by ellipticview** [comment]
I didn't explicitly install Visual Studio. The node-gyp instructions were followed, option 1:
```
npm install --global windows-build-tools
```

The following step then does not work:
```
C:\A0\yarle-master>node-gyp configure
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
```

This is really too complicated. Would be much better to use a node.js XML parser that does not have the C++ dependency.

**Comment by akosbalasko** [comment]
This error occurs during the installation of node-gyp,  so please raise it on their repo.

After a detailed research I did not find any native xml parser which moreover

**Comment by akosbalasko** [comment]
This error occurs during the installation of node-gyp,  so please raise it on their repo.

After a detailed research I did not find any native xml parser which moreover parses xml as a stream and has a good performance as well, but feel free to offer a package that probably missed my attention. Thank you.

**Comment by akosbalasko** [comment]
btw I'm thinking on an enhancement that offers the app as a Docker image. This would resolve any platform-dependent rebuild what causes the current problem.

**Comment by ellipticview** [comment]
As yarle would usually be a one-time conversion, it would benefit from a simple installation. Even Docker is extremely heavyweight as a prerequisite for someone (who is possibly not a developer) to convert a set of files.
In the meantime, I'll be using Joplin to import ENEX and export markdown.

**Comment by akosbalasko** [comment]
Sure, go ahead.
