### ISSUE TITLE
--configFile file doesn't accept absolute path?

### ISSUE THREAD

**Issue by luckman212** [akosbalasko/yarle#186]
- macOS 11.1
- npm/npx 7.4.2
- my config is at `~/.yarle/config.json`

**works** (relative path):

    $ echo $PWD
    /Users/luke
    $ npx -p yarle-evernote-to-md@latest yarle --configFile .yarle/config.json

**doesn't** work:

    $ npx -p yarle-evernote-to-md@latest yarle --configFile /Users/luke/.yarle/config.json

Is this expected? I don't want to have to be in any particular directory in order to specify my config file... 

error output:

```
Loading config from /Users/luke//Users/luke/.yarle/config.json
node:internal/modules/cjs/loader:925
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/luke//Users/luke/.yarle/config.json'
Require stack:
- /Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js
- /Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRope.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.exports.run (/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js:18:53)
    at Object.<anonymous> (/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRope.js:14:19)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js',
    '/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/dropTheRope.js'
  ]
}
npm ERR! code 1
npm ERR! path /Users/luke
npm ERR! command failed
npm ERR! command sh -c yarle "--configFile" "/Users/luke/.yarle/config.json"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/luke/.npm/_logs/2021-01-21T15_40_36_046Z-debug.log
```

**Comment by akosbalasko** [comment]
HI @luckman212 !

Yes, it is expected, these folders must be specified as relative folders.

**Comment by luckman212** [comment]
Thank you @akosbalasko - any chance you would consider supporting absolute paths in the future?

**Comment by akosbalasko** [comment]
Hi @luckman212 , Sure, sure, sorry for the delay, my other projects require more attention currently. But definitely I'll implement this feat. soon, hopefully during this week.

**Comment by luckman212** [comment]
Thank you @akosbalasko ... certainly there is no rush

**Comment by akosbalasko** [comment]
Hi @luckman212 , I release a new version(3.9.1) that now supports absolute paths.

**Comment by luckman212** [comment]
Excellent! I will give it a try, thank you 👍
