### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error

### ISSUE THREAD

**Issue by php-programmist** [akosbalasko/yarle#198]
Node.js version - 14.16.0
Every time when I start command
`npx -p yarle-evernote-to-md@latest yarle --configFile config.json`

I have this error on Windows 10 Home x64:
```
Loading config from D:\Obsidian/config.json
Converting notes in file: D:\Obsidian\Enex\Test.enex
(node:31816) UnhandledPromiseRejectionWarning: Error: D:\Obsidian\Notes/notes/D:\Obsidian\Enex\Test contains invalid WIN32 path characters.
    at Object.mkdirsSync (C:\Users\Alexey\AppData\Roaming\npm-cache\_npx\43580\node_modules\yarle-evernote-to-md\node_modules\fs-extra\lib\mkdirs\mkdirs-sync.js:18:22)
    at Object.exports.setPaths (C:\Users\Alexey\AppData\Roaming\npm-cache\_npx\43580\node_modules\yarle-evernote-to-md\dist\utils\folder-utils.js:79:24)
    at Object.exports.dropTheRope (C:\Users\Alexey\AppData\Roaming\npm-cache\_npx\43580\node_modules\yarle-evernote-to-md\dist\yarle.js:109:11)
    at Object.exports.run (C:\Users\Alexey\AppData\Roaming\npm-cache\_npx\43580\node_modules\yarle-evernote-to-md\dist\dropTheRopeRunner.js:26:21)
    at Object.<anonymous> (C:\Users\Alexey\AppData\Roaming\npm-cache\_npx\43580\node_modules\yarle-evernote-to-md\dist\dropTheRope.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:31816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:31816) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
My config.json:
```json
{
    "enexSource": "D:\\Obsidian\\Enex\\Test.enex",
    "templateFile":"",
    "outputDir": "D:\\Obsidian\\Notes",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "ObsidianMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": true,
    "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}
```
Test.enex:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE en-export SYSTEM "http://xml.evernote.com/pub/evernote-export3.dtd">
<en-export export-date="20210407T090819Z" application="Evernote" version="10.8.5">
  <note>
    <title>Test</title>
    <created>20210307T090753Z</created>
    <updated>20210307T090804Z</updated>
    <note-attributes>
      <author>Alexey</author>
    </note-attributes>
    <content>
      <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE en-note SYSTEM "http://xml.evernote.com/pub/enml2.dtd"><en-note><div>test</div></en-note>      ]]>
    </content>
  </note>
</en-export>
```

What I am doing wrong?

**Comment by php-programmist** [comment]
Problem solved when I changed paths in config.json
From:
D:\\Obsidian\\Enex\\Test.enex
D:\\Obsidian\\Notes
To
/Obsidian/Enex/Test.enex
/Obsidian/Notes
