### ISSUE TITLE
Examples of config file and execution statement

### ISSUE THREAD

**Issue by ColinWilder** [akosbalasko/yarle#202]
I'm pretty new to this and am having trouble customizing my config.json file to my local machine. Here are some questions: 
Do these look like well-formed versions of the first three lines of config.json?
```
    "enexSource": "D:/Writing/GitHub/zettelkasten/enexExportFiles/OCLC plan hatch.enex",
    "templateFile": "D:/Writing/GitHub/zettelkasten/yarle/default-template",
    "outputDir": "out",

```
Or could I even omit the templateFile line, in order to force yarle to use the default template? 

For the execution statement, could it look like this?
`npx -p yarle-evernote-to-md@latest yarle --"D:/Writing/GitHub/zettelkasten/yarle/config.json"
`

**Comment by ColinWilder** [comment]
Hi, I hope it's not inappropriate for me to use an issue forum to ask questions. I cannot find any other help on the internet for yarle. I figured out to use the following command: 
`npx -p yarle-evernote-to-md@latest yarle --configFile <D:/Writing/GitHub/zettelkasten/yarle/config.json>`
...but now I get an error message saying:
`Failed to convert note: sampleNoteName TypeError: Cannot read property 'replace' of undefined`
What does this mean?

**Comment by ColinWilder** [comment]
Here's the full command and error message, for the Evernote export file "OCLC-plan-hatch.enex":

```
PS D:\Writing\GitHub\zettelkasten\yarle> npx -p yarle-evernote-to-md@latest yarle --configFile D:/Writing/GitHub/zettelkasten/yarle/config.json
Loading config from D:/Writing/GitHub/zettelkasten/yarle/config.json
Converting notes in file: OCLC-plan-hatch.enex


Started conversion: Sun Mar 14 2021 19:05:00 GMT-0400 (Eastern Daylight Time)
Converting note "OCLC plan hatch"...
Failed to convert note: OCLC plan hatch TypeError: Cannot read property 'replace' of undefined
    at Object.exports.convertHtml2Md (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\dist\convert-html-to-md.js:32:33)
    at Object.exports.processNode (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\dist\process-node.js:27:84)
    at EventEmitter.<anonymous> (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\dist\yarle.js:90:32)
    at EventEmitter.emit (events.js:315:20)
    at SAXStream.<anonymous> (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\xml-flow\lib\xml-flow.js:142:15)
    at SAXStream.emit (events.js:315:20)
    at SAXParser.me._parser.<computed> [as onclosetag] (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:258:17)
    at emit (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:889:7)
Finished conversion: Sun Mar 14 2021 19:05:00 GMT-0400 (Eastern Daylight Time)
Note "OCLC plan hatch" converted successfully in 0.01 seconds.
Notes processed: 1


==========================
Conversion finished: 1 succeeded, 0 skipped, 0 failed. Total notes: 1
```

The output directory structure of "D:\Writing\GitHub\zettelkasten\yarle\out\notes\OCLC-plan-hatch\_resources" gets built but no ,.md or any other file shows up in it...

I also note that "C:\Users\Colin\AppData\Roaming\npm-cache\_npx\7592\node_modules\yarle-evernote-to-md\node_modules\sax\lib\" does not exist; there is nothing in ""C:\Users\Colin\AppData\Roaming\npm-cache\_npx\". Node.js is installed in my program files, not in "C:\Users\Colin\". Help?!

**Comment by akosbalasko** [comment]
Hi @ColinWilder !

Could you please share your whole config.json file located here: D:/Writing/GitHub/zettelkasten/yarle/config.json

It looks that Yarle founds the enex file, so its path is correct, but I think it misses to find the template file in the specified place, but this is just a feeling, I would like to check it in the config. 

In order to set the template correctly, please create a file named `template.tmpl` in folder`D:/Writing/GitHub/zettelkasten/yarle`  with the following content: 
```typescript 
export const defaultTemplate = `{title-block}# {title}{end-title-block}
{tags-block}
---
Tag(s): {tags}
---
{end-tags-block}
{content-block}{content}{end-content-block}
{created-at-block}    Created at: {created-at}{end-created-at-block}
{updated-at-block}    Updated at: {updated-at}{end-updated-at-block}
{source-url-block}    Source URL: {source-url}{end-source-url-block}
{location-block}    Where: {location}{end-location-block}
`;
```

Then the line of the template's path in the config file must be updated by "templateFile": "D:/Writing/GitHub/zettelkasten/yarle/template.tmp"

**Comment by ColinWilder** [comment]
Hi @ akosbalasko! Thanks for writing back to me. 

I've altered my template and config files. 

Here's my template file, "template.tmpl" now:

```
export const defaultTemplate = `{title-block}# {title}{end-title-block}
{tags-block}
---
Tag(s): {tags}
---
{end-tags-block}
{content-block}{content}{end-content-block}
{created-at-block}    Created at: {created-at}{end-created-at-block}
{updated-at-block}    Updated at: {updated-at}{end-updated-at-block}
{source-url-block}    Source URL: {source-url}{end-source-url-block}
{location-block}    Where: {location}{end-location-block}
`;
```

Here's my config.json file:

```
{
    "enexSource": "enexExportFiles",
    "templateFile": "template.tmpl",
    "outputDir": "out",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "StandardMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}
```

Here's what happens:
```
PS D:\Writing\GitHub\zettelkasten\yarle> npx -p yarle-evernote-to-md@latest yarle --configFile D:/Writing/GitHub/zettelkasten/yarle/config.json
Loading config from D:/Writing/GitHub/zettelkasten/yarle/config.json
Converting notes in file: OCLC-plan-hatch.enex
(node:14436) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'template.tmpl'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at setOptions (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\868\node_modules\yarle-evernote-to-md\dist\yarle.js:45:33)
    at Object.exports.dropTheRope (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\868\node_modules\yarle-evernote-to-md\dist\yarle.js:108:5)
    at Object.exports.run (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\868\node_modules\yarle-evernote-to-md\dist\dropTheRopeRunner.js:38:25)
    at Object.<anonymous> (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\868\node_modules\yarle-evernote-to-md\dist\dropTheRope.js:14:19)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14436) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:14436) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
PS D:\Writing\GitHub\zettelkasten\yarle>
```

Nothing at all appears in the output folder called "out". 

What do you think is going wrong?

**Comment by akosbalasko** [comment]
Hi @ColinWilder !
The error says that it cannot find the template file in the given location.

So, please use absolute paths where you specify enexSource and templateFile in your config. 
So, assuming that your enex and template are in D:\Writing\GitHub\zettelkasten\yarle , your config file should look like this:
```
{
    "enexSource": "D:\Writing\GitHub\zettelkasten\yarle\enexExportFiles",
    "templateFile": "D:\Writing\GitHub\zettelkasten\yarle\template.tmpl",
    "outputDir": "out",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "StandardMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}
```
Hope it will start working for you properly.

**Comment by ColinWilder** [comment]
I'm very sorry, but still No! Thanks so much for your help; here is my new config.json:
```
{
    "enexSource": "D:/Writing/GitHub/zettelkasten/yarle/enexExportFiles",
    "templateFile": "D:/Writing/GitHub/zettelkasten/yarle/template.tmpl",
    "outputDir": "out",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "StandardMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}
```
and here is the error code I receive in Windows Power Shell:
```
PS D:\Writing\GitHub\zettelkasten\yarle> npx -p yarle-evernote-to-md@latest yarle --configFile config.json
Loading config from D:\Writing\GitHub\zettelkasten\yarle/config.json
Converting notes in file: test.enex


Started conversion: Tue Mar 16 2021 14:58:13 GMT-0400 (Eastern Daylight Time)
Converting note "test"...
Failed to convert note: test TypeError: Cannot read property 'replace' of undefined
    at Object.exports.convertHtml2Md (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\dist\convert-html-to-md.js:32:33)
    at Object.exports.processNode (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\dist\process-node.js:27:84)
    at EventEmitter.<anonymous> (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\dist\yarle.js:90:32)
    at EventEmitter.emit (events.js:315:20)
    at SAXStream.<anonymous> (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\node_modules\xml-flow\lib\xml-flow.js:142:15)
    at SAXStream.emit (events.js:315:20)
    at SAXParser.me._parser.<computed> [as onclosetag] (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:258:17)
    at emit (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Users\Colin\AppData\Roaming\npm-cache\_npx\14040\node_modules\yarle-evernote-to-md\node_modules\sax\lib\sax.js:889:7)
Finished conversion: Tue Mar 16 2021 14:58:13 GMT-0400 (Eastern Daylight Time)
Note "test" converted successfully in 0.04 seconds.
Notes processed: 1


==========================
Conversion finished: 1 succeeded, 0 skipped, 0 failed. Total notes: 1
PS D:\Writing\GitHub\zettelkasten\yarle>
```

Could it be a problem with slash vs backslash? Power shell? Spaces in file or folder names? 

You'll notice I changed the name of the test .enex file to simply "test". 

This seems to be the nub: the error message part which says `TypeError: Cannot read property 'replace' of undefined`

**Comment by akosbalasko** [comment]
Hm, the folders and files sound good as the converter finds `test.enex` to be converted, and start with a note called `test` in it. 
So, it's really strange, it looks like that the html format of 'test' note is missing. 
May I ask you to send me the enex file for further investigation? here is my email address: akos0215@gmail.com
Thank you, and sorry for the troubles.

**Comment by ColinWilder** [comment]
Of course! Thank you so much! See attached. LMK if the attachment does not get to you. 

Thanks!

Colin Wilder

**Comment by akosbalasko** [comment]
Hi @ColinWilder, 
Nope, attachments should be zipped, or you can mail me directly via : akos0215@gmail.com

thank you!

**Comment by akosbalasko** [comment]
For the record: The problem was that the Enex file was exported using EN v10, which uses a different format to store the notes in XML. A long term solution is to improve Yarle to deal with the new format as well, but as a short-term workaround I suggest to install the legacy EN, export the notes from there, which will transform notes into the format that is readable by Yarle.
