### ISSUE TITLE
Could not find the "utimes" binary, have you run npm install?

### ISSUE THREAD

**Issue by luckman212** [akosbalasko/yarle#261]
With latest yarle v4.0.7, when trying to run with npx, I get

```console
$ npx -p yarle-evernote-to-md@latest yarle
/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:11
	throw new Error('Could not find the "utimes" binary, have you run npm install?');
	^

Error: Could not find the "utimes" binary, have you run npm install?
    at Object.<anonymous> (/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/utimes/src/utimes/index.js:11:8)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Function.Module._load (node:internal/modules/cjs/loader:828:14)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/Users/luke/.npm/_npx/106a035a6ccf201d/node_modules/yarle-evernote-to-md/dist/utils/content-utils.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
```

Manually `cd` into `/Users/luke/.npm/_npx/106a035a6ccf201d/` and then running `npm i utimes --force` I was able to get it to run, but that spit out a LOT of errors...

**Comment by akosbalasko** [comment]
Hi @luckman212 , which OS do you run it? afaik utimes has precompiled versions for each, so it looks like that an OS upgrade requires utimes release a build for that as well.

**Comment by luckman212** [comment]
Oh sorry, it's macOS 11.2.3

**Comment by akosbalasko** [comment]
Hm... I don't really know, I don't remember any changes relevant in this case. I have to compare the two versions to see the differences.

**Comment by akosbalasko** [comment]
Btw the latest version is 4.0.9, and of course it has the same problem.

**Comment by akosbalasko** [comment]
Ok, I think the most simple way to avoid this would be to replace npx command by the electron's command line option. Simply just allow to set command line arguments to the same executable.

**Comment by luckman212** [comment]
So for that you mean download the full Electron version and then just call it from the commandline?

**Comment by akosbalasko** [comment]
@luckman212 yepp, this would be the plan. Btw by npx you download everything as well, it just stores the stuff in a temp directory.

**Comment by luckman212** [comment]
Hey @akosbalasko I downloaded Yarle 4.0.9 (full Electron app) for Mac/darwin and I'm struggling to make it run on the commandline. Is there a certain syntax?

I am trying:

```
/Applications/yarle-evernote-to-md.app/Contents/MacOS/yarle-evernote-to-md --configFile /path/to/my/config.json
```

It is ignoring my config file and just opening in full GUI mode...

**Comment by akosbalasko** [comment]
Hi @luckman212 , 
Sorry I was misunderstandable. This is still a plan, I have to move the config recognition part and everything to there. So it is still not implemented yet. 
Btw the syntax is good, it will work with this command line arguments and syntax.

**Comment by ColdDevil** [comment]
Had the same issue with utimes.. Using node v16 worked for me:

- `nvm install 16` or `nvm use 16`
- `npm i yarle-evernote-to-md@latest`
- `npx yarle --configFile ./export-config.json`

Long story: First I had an issue with icu4c (see https://stackoverflow.com/questions/67169683/dyld-library-not-loaded-usr-local-opt-icu4c-lib-libicui18n-67-dylib) which was solved by `brew reinstall icu4c`.. Then the utimes issue came up and I was able to manually build the binary by doing this after installing yarle:

- `cd node_modules/utimes`
- `npm run install --update-binary`
- `ln -s /path/to/your/node_modules/utimes/lib/binding/Release/node-v88-darwin-x64/utimes.node /path/to/your/node_modules/.bin/utimes`

...but that left me with a type error (could not cast undefined or null to object). So using node v16 helped in the end! :)
