### ISSUE TITLE
Some errors when converting notes

### ISSUE THREAD

**Issue by JonLaliberte** [akosbalasko/yarle#39]
Thanks for writing this, it largely worked great, most files converted perfectly. 

I had just a handful fail with errors. I put at least one of each error I received below.

Separate from fixing the errors, it'd be great if the app tracked these and printed a summary of those that failed to convert at the end of the process.

---

Failed to convert note: # Vehicle Identification Number VIN
 TypeError: Cannot read property 'value' of undefined
    at Object.replacement (/Users/jon/Dropbox/Development/Mac/yarle/dist/utils/turndown-rules/images-rule.js:12:40)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:878:10)
    at /Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:837:40
    at NodeList.reduce (<anonymous>)
    at TurndownService.process (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:830:17)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:873:25)
    at /Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:837:40
    at NodeList.reduce (<anonymous>)
    at TurndownService.process (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:830:17)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:873:25)
Note # Vehicle Identification Number VIN
 converted successfully.

---

Failed to convert note: # Stuff to bring to hotel for pub crawl
 TypeError: Cannot read property 'value' of undefined
    at Object.replacement (/Users/jon/Dropbox/Development/Mac/yarle/dist/utils/turndown-rules/task-items-rule.js:9:38)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:878:10)
    at /Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:837:40
    at NodeList.reduce (<anonymous>)
    at TurndownService.process (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:830:17)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:873:25)
    at /Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:837:40
    at NodeList.reduce (<anonymous>)
    at TurndownService.process (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:830:17)
    at TurndownService.replacementForNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:873:25)
Note # Stuff to bring to hotel for pub crawl
 converted successfully.

---
Another one was:
Failed to convert note: # Quotation for X
 TypeError: <?xml version="1.0" encoding="UTF-8" standalone="no"?>...
It was the whole file I believe. 

Then: 
is not a string, or an element/document/fragment node.
    at TurndownService.turndown (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/turndown/lib/turndown.cjs.js:735:13)
    at Object.exports.convertHtml2Md (/Users/jon/Dropbox/Development/Mac/yarle/dist/convert-html-to-md.js:5:65)
    at Object.exports.processNode (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-node.js:24:47)
    at EventEmitter.xmlStream.on (/Users/jon/Dropbox/Development/Mac/yarle/dist/yarle.js:25:28)
    at EventEmitter.emit (events.js:197:13)
    at SAXStream.saxStream.on.tagName (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/xml-flow/lib/xml-flow.js:142:15)
    at SAXStream.emit (events.js:197:13)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:258:17)
    at emit (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:629:5)

---

Failed to convert note: # Whatever Pictures
 TypeError: Cannot read property '$text' of undefined
    at processResource (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-resources.js:43:32)
    at Object.exports.processResources (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-resources.js:14:79)
    at Object.exports.processNode (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-node.js:22:43)
    at EventEmitter.xmlStream.on (/Users/jon/Dropbox/Development/Mac/yarle/dist/yarle.js:25:28)
    at EventEmitter.emit (events.js:197:13)
    at SAXStream.saxStream.on.tagName (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/xml-flow/lib/xml-flow.js:142:15)
    at SAXStream.emit (events.js:197:13)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:258:17)
    at emit (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:629:5)
Note # Whatever Pictures
 converted successfully.

---

Failed to convert note: # The psychology of
 TypeError: Cannot read property '$text' of undefined
    at processResource (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-resources.js:43:32)
    at Object.exports.processResources (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-resources.js:19:75)
    at Object.exports.processNode (/Users/jon/Dropbox/Development/Mac/yarle/dist/process-node.js:22:43)
    at EventEmitter.xmlStream.on (/Users/jon/Dropbox/Development/Mac/yarle/dist/yarle.js:25:28)
    at EventEmitter.emit (events.js:197:13)
    at SAXStream.saxStream.on.tagName (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/xml-flow/lib/xml-flow.js:142:15)
    at SAXStream.emit (events.js:197:13)
    at SAXParser.me._parser.(anonymous function) [as onclosetag] (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:258:17)
    at emit (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/jon/Dropbox/Development/Mac/yarle/node_modules/sax/lib/sax.js:629:5)
Note # The psychology of 
 converted successfully.

**Comment by akosbalasko** [comment]
Hi @JonLaliberte! Thanks for trying the app and for the report as well. I'll investigate them and let you updated asap.
++ Thank you for the feat. request about tracking the failed conversions, it definitely makes sense, so probably I'll implement it in the next release.

**Comment by akosbalasko** [comment]
Dear @JonLaliberte! 
Version 2.9.0 is out with the implemented feature request and the fix of this issue. 
@rodbv thank you for sorting this out!

**Comment by JonLaliberte** [comment]
@akosbalasko Nice, thanks @rodbv !
