### ISSUE TITLE
Error: Cannot find module 'minimist'

### ISSUE THREAD

**Issue by rdoering** [akosbalasko/yarle#397]
$ npx  yarle-evernote-to-md@4.10.1 yarle                                                                           [17:14:24]
Need to install the following packages:
  yarle-evernote-to-md@4.10.1
Ok to proceed? (y) y
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
logfilepath: /Users/robert/Library/Application Support/yarle-evernote-to-md/conversion.log
clearing log: /Users/robert/Library/Application Support/yarle-evernote-to-md/conversion.log
node:internal/modules/cjs/loader:946
  const err = new Error(message);
              ^

Error: Cannot find module 'minimist'
Require stack:
- /Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js
- /Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRope.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:946:15)
    at Module._load (node:internal/modules/cjs/loader:787:27)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.run (/Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js:34:18)
    at Object.<anonymous> (/Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRope.js:26:19)
    at Module._compile (node:internal/modules/cjs/loader:1112:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:834:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRopeRunner.js',
    '/Users/robert/.npm/_npx/f66a07d5d96a1351/node_modules/yarle-evernote-to-md/dist/dropTheRope.js'
  ]
}

Node.js v18.5.0
FAIL

**Comment by akosbalasko** [comment]
Hi @rdoering, oops sorry, I'll fix it soon.

**Comment by akosbalasko** [comment]
I added it in version 4.10.2, please check it out.
Thank you for raising this up!
