### ISSUE TITLE
npm i failing

### ISSUE THREAD

**Issue by steveraysteveray** [akosbalasko/yarle#40]
I'm running macOS Catalina 10.15.5, and tried downloading the zip file.
I unzipped it, and from the yarle-master folder tried running 'npm i'
It gave a number of errors (see attached file)

'node -v' shows: v12.18.0

Any suggestions?
[yarle-install.txt](https://github.com/akosbalasko/yarle/files/4841307/yarle-install.txt)

**Comment by akosbalasko** [comment]
Hi @steveraysteveray ,

Please downgrade your Node to 10.18.1.

Cheers,
akos

**Comment by steveraysteveray** [comment]
Thanks. Things are better, but still errors:
[yarle-install.txt](https://github.com/akosbalasko/yarle/files/4842467/yarle-install.txt)

**Comment by akosbalasko** [comment]
Please reinstall node-gyp by typing:
`npm install node-gyp@latest`

**Comment by steveraysteveray** [comment]
Looks like 'request" is deprecated, with alternatives at: https://github.com/request/request/issues/3142


Here's what I got for 'npm install node-gyp@latest:
``` text
npm install node-gyp@latest
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> node-expat@2.3.18 install /Volumes/Bulk/Downloads/yarle-master/node_modules/node-expat
> node-gyp rebuild

  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlparse.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmltok.o
  CC(target) Release/obj.target/expat/deps/libexpat/lib/xmlrole.o
  LIBTOOL-STATIC Release/libexpat.a
  CXX(target) Release/obj.target/node_expat/node-expat.o
  SOLINK_MODULE(target) Release/node_expat.node

> iconv@2.3.5 install /Volumes/Bulk/Downloads/yarle-master/node_modules/iconv
> node-gyp rebuild

  CXX(target) Release/obj.target/iconv/src/binding.o
  CC(target) Release/obj.target/iconv/deps/libiconv/lib/iconv.o
  CC(target) Release/obj.target/iconv/support/localcharset.o
  SOLINK_MODULE(target) Release/iconv.node

> @ronomon/utimes@2.3.0 install /Volumes/Bulk/Downloads/yarle-master/node_modules/@ronomon/utimes
> node-gyp rebuild

Traceback (most recent call last):
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/steveray/.nvm/versions/node/v10.18.1/bin/node" "/Users/steveray/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Volumes/Bulk/Downloads/yarle-master/node_modules/@ronomon/utimes
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ronomon/utimes@2.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ronomon/utimes@2.3.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/steveray/.npm/_logs/2020-07-01T17_16_05_110Z-debug.log
```

**Comment by akosbalasko** [comment]
How about following these suggestions?: 

https://github.com/nodejs/node-gyp/issues/1917#issuecomment-552101171

**Comment by steveraysteveray** [comment]
They worked! Thanks.
