### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by eharvey71** [akosbalasko/yarle#465]
I'm getting this error:

```
C:\Users\eharv\AppData\Local\npm-cache\_npx\106a035a6ccf201d\node_modules\yarle-evernote-to-md\dist\dropTheRopeRunner.js:46
    if (options.enexSources.length === 1 && options.enexSources[0].endsWith('.enex')) {
                            ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Object.run (C:\Users\eharv\AppData\Local\npm-cache\_npx\106a035a6ccf201d\node_modules\yarle-evernote-to-md\dist\dropTheRopeRunner.js:46:29)
    at Object.<anonymous> (C:\Users\eharv\AppData\Local\npm-cache\_npx\106a035a6ccf201d\node_modules\yarle-evernote-to-md\dist\dropTheRope.js:30:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12)
    at node:internal/main/run_main_module:23:47
```

Here's the name of my enex file:
ClassFindr-DevEnv.enex

Config.json looks like this:
```
{
    "enexSource": "/c/Users/eharv/dev/convert_evernote_to_md/ClassFindr-DevEnv.enex",
    "outputDir": "./",
    "isZettelkastenNeeded": false,
    "plainTextNotesOnly": false,
    "skipWebClips": false,
    "useHashTags": true,
    "outputFormat": "StandardMD",
    "urlEncodeFileNamesAndLinks": false,
    "skipEnexFileNameFromOutputPath": false,
    "haveEnexLevelResources": false,
    "monospaceIsCodeBlock": false,
    "keepMDCharactersOfENNotes": false,
    "nestedTags": {
      "separatorInEN": "_",
      "replaceSeparatorWith": "/",
      "replaceSpaceWith": "-"
   }
}

```

**Comment by akosbalasko** [comment]
hi @eharvey71 ,
Your config doesn't seem to be correct. Instead of "enexSource", the correct property to specify your enex file is **enexSources**, which is an array. 
so, the correct one should be: 

enexSources: ["absolute-path-to-your-enex-file.enex"]

**Comment by eharvey71** [comment]
Thanks. The owner of this blog post will need to update with the correct config info:
https://compile.blog/evernote-enex-to-md/
